### ISSUE TITLE
erro message

### ISSUE THREAD

**Issue by cryoguy** [jboone/gr-tpms#15]
Did anybody encounter following error:

tpms_rx --source rtlsdr --if-rate 400000 --tuned-frequency 315000000
Traceback (most recent call last):
  File "/usr/local/bin/tpms_rx", line 37, in <module>
    import tpms
ImportError: No module named tpms

**Comment by parkerlreed** [comment]
You have to set the install prefix to /usr. Default /usr/local looks for python modules in /usr/local/lib/python* which doesn't exist.

At the `cmake ..` step use this

    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..

**Comment by cryoguy** [comment]
working now. Thanks!
