### ISSUE TITLE
Need a help on own TPMS project.

### ISSUE THREAD

**Issue by belusiak** [jboone/gr-tpms#9]
Hi,
I watched your video and I am impressed of your project and knowledge about RF communication.

I want to implement TPMS reader on my GPS tracker using a radio which is on it. This radio is a RFM12B (http://www.hoperf.com/upload/rf/RFM12B.pdf) so I have to use some 433Mhz (Europe standard) transmitters with FSK modulation.

I bought two common and popular on Europe cars transmitters for testing.
![2016-03-24 15 35 14](https://cloud.githubusercontent.com/assets/18052605/14025608/3d56e04a-f1ef-11e5-9f45-85f86e0ced10.jpg)

Now I do not even know if these modulation is FSK or not. I found some information on FCC searches (https://fccid.io/document.php?id=2506529) but for example on shredder devices there are two different information (page 6 and page 14). Probably I understand something wrong.
Normally RFM12B in my device works on 869MHz but of course I use other hardware version which is 433Mhz.

I set RFM12B to 433,92Mhz and 67kHz bandwidth but I read a lot of noise on all bit rate. In normal situation I use two byte match patter to recognize start of transmission but in this situation I cannot use it. To test I use remote for garage gate and I can see difference in transmission but I cannot find it packet correctly probably because of bad bit rate or cause of noise.

Could you please look at FCC documents and give me some advice how to set RFM12B. I hope that the use of this radio is not a totally bad idea? What do you think about that?

Thank in advance for any help
Regards
Michał

**Comment by bgolab** [comment]
Hi,
I am also thinking about RFM-based (RFM12B, RFM69W) receiver for TPMS. I wonder if you managed to build such receiver?

Thanks,
Bogdan
